const interviews = {
    rogerfritz: {
        id: "rogerfritz",
        person: "Roger Fritz",
        coordinates: {
            lng: 8.680000,
            lat: 50.110000
        },
        color: "rgb(238, 138, 30)",
        title: "Wir sind dort einfach hingegangen, haben die Kamera aufgestellt, schnell gedreht und sind dann wieder weg",
        subtitle: "Der Regisseur Roger Fritz über seinen Film 'Frankfurt Kaiserstraße'",
        tag: "Frankfurt als Nachtasyl",
        intro: "1981 erscheint mit 'Frankfurt Kaiserstraße' ein Film von Roger Fritz, der damals als Milieustudie so raffiniert war, wie er heute als dokumentarische Zeitkapsel funktioniert. Wenngleich das Frankfurter Bahnhofsviertel vordergründig als Schablone dient, um die Figuren im sumpfigen Zwielicht lernen zu lassen, dass es die ersehnte Freiheit bloß im sich widerstreitenden Plural gibt, gelingt ihm doch zugleich ein Porträt dieses großstädtischsten aller Frankfurter Stadtviertel, seiner Straßenzüge, Etablissements, Kleidermoden und Sprechweisen. Der 1936 geborene Roger Fritz ist nicht nur Regisseur mehrerer Filme und zahlreicher Fernsehserien, sondern ebenso ausgebildeter Schauspieler und vor allem Fotograf. Er assistierte Luchino Visconti bei 'Boccaccio 70' und 'Il Gattopardo', arbeitete für Gian Carlo Menotti in New York, spielte bei Fassbinder und fotografierte Andy Warhol, Romy Schneider oder die Beatles. Im Gespräch schildert er seine Drehstrategie, die von einer zurückhaltenden Polizei profitierte, berichtet von einem gewonnenen Rückwärtsautorennen in Frankfurt, wo das Filmmuseum seinen Film später nicht zeigen wollte und erklärt, warum er 'Frankfurt Kaiserstraße' lieber in Hamburg gedreht hätte.",
        pictureDescription: "Von links nach rechts: Hannes A., Berta B., Cäsar C. und Doris D. Foto: Hannes Meyer.",         
        interviewContent: [
            "Nachdem Sie Ende der 1960er Jahre gleich drei Spielfilme drehten, traten Sie als Regisseur in den Folgejahren allein mit Fernsehserien in Erscheinung. Erst 1981 kam mit 'Frankfurt Kaiserstraße' ein weiterer Film von Ihnen in die Kinos. Was brauchte es, damit Sie sich wieder zu einem Spielfilm durchringen konnten?",
            "Ich habe mich nicht durchgerungen. Das funktioniert beim Film so nicht. Ein Film kostet ein Schweinegeld, da braucht es immer jemanden, der ihn finanziert. Dass ich über zehn Jahre keinen Spielfilm mehr gedreht habe, hing bestimmt auch damit zusammen, dass ich meine vorherigen Filme allesamt selbst produzierte. Vor so jemandem haben andere Verleiher einen Riesen-Respekt. In dem konkreten Fall kam dann Karl Spiehs von Lisa-Film auf mich zu und fragte, ob ich 'Frankfurt Kaiserstraße' machen will. Das Drehbuch lag vor und auch die Rollen waren bereits besetzt.",      
            "Lisa-Film produzierte für den Massenmarkt, hauptsächlich leicht verdauliche Komödien und Erotikfilme. Wie passte Ihr Film in dieses Portfolio?",
            "Die haben sich da sicherlich etwas ganz anderes drunter vorgestellt als das, was nachher aus dem Film geworden ist. Es war nicht leicht, den Film zu drehen. Ich hatte mit vielen Widerständen zu kämpfen. Das fing schon damit an, dass ich entgegen der eigentlichen Besetzung den Wiener Schauspieler Hanno Pöschl dazu holte. Wobei ich das immerhin noch vermitteln konnte, weil Lisa-Film schließlich eine deutsch-österreichische Produktion war. Aber auch die Rollen der beiden Hauptfiguren Susanne und Rolf habe ich neu besetzt. Den männlichen Part sollte eigentlich Heiner Lauterbach spielen, der mir für die Rolle zu erwachsen war. Ich entschied mich für das Modell Michaela Karger und den Musiker Dave Balko, die mit Schauspielerei rein gar nichts am Hut hatten und danach auch nicht mehr als Schauspieler in Erscheinung getreten sind. Darüber hinaus habe ich noch während des Drehs fast alles am Drehbuch und dessen Texten verändert.",
            "War es Ihre Entscheidung, in Frankfurt zu drehen?",
            "Das lag schlichtweg daran, dass das Drehbuch, das bereits existierte, in Frankfurt spielte. Wenn ich Einfluss auf den Drehort hätte nehmen können, wäre mein Film wohl in Hamburg auf St.Pauli entstanden. Denn St. Pauli kannte ich in- und auswendig, dort hatte ich für verschiedene Serien gearbeitet. Klar wurde damals von Frankfurt als dem 'deutschen Chicago' gesprochen, aber das war doch ziemlicher Quatsch. Immerhin lieferte das Bahnhofsviertel um die Kaiserstraße die Kulisse dafür. Und mir kam zugute, dass ich jemanden aus der Frankfurter Unterwelt kannte, so dass ich in den entsprechenden Lokalitäten drehen konnte.",
            "Welche Verbindung hatten Sie ansonsten in die Mainmetropole?",
            "Obwohl ich aus Mannheim bin, hatte ich biographisch zu Frankfurt keine große Beziehung. Ich war nie für eine längere Zeit in der Stadt, sondern immer nur ganz gezielt im Rahmen irgendwelcher Veranstaltungen. Ich habe in Frankfurt mal mit einem Alfa Romeo ein Rückwärtsautorennen gewonnen, für das ganz offiziell eine Straße abgesperrt wurde. Das war noch ein paar Jahre bevor ich den Film drehte. Später wiederum gab es im Filmmuseum am Mainufer mal eine Ausstellung über mich, in deren Rahmen auch meine Filme gezeigt werden sollten. 'Frankfurt Kaiserstraße' fanden sie so beschissen, dass sie ihn einfach weggelassen haben.",
            "Und Sie, wie finden Sie Ihren Film?",
            "Als der Film fertig war, war ich nicht so begeistert. Erst später begann ich den Film zu mögen.",
            "Eine Qualität Ihres Film ist zweifellos seine nahbare, sehr direkte Bildsprache, die zugleich sehr komponiert wirkt. Er arrangiert die Straßenzüge und Etablissements der zwielichtigen Lebenswelten so ausführlich und direkt wie ein Dokumentarfilm und ist doch so ästhetisch wie es nur ein Spielfilm sein konnte.",
            "Bevor ich in Berlin auf die Ufa-Nachwuchsschule ging, war ich schon ein verhältnismäßig bekannter Fotograf. Die Fotografie hat mich bei meiner Filmarbeit von Beginn an sehr beeinflusst. 'Frankfurt Kaiserstraße' profitiert sicherlich auch von meinen vorherigen Fotoreportagen über das Rotlicht. Von der Fotografie kommend entstand für mich ein ganz anderer innerer Aufbau als bei jemandem, der nur von der Sprache und der Regie her denkt. Wenn ich in einen Raum komme, sehe ich die Szene bereits, sehe, wo sie spielt. Wahrscheinlich sind meine Filme deshalb auch ein bisschen realer als die der anderen Jungfilmer zu jener Zeit. Einen Kameramann hätte ich deshalb eigentlich gar nicht gebraucht, sondern bloß einen Assistenten.",
            "Hatten Sie auch in Frankfurt zuvor einmal fotografiert?",
            "Für das von mir mitgegründete Twen-Magazin habe ich mal eine Reportage mit zwei jungen Leuten gemacht, die zeigt, wie man für 5, 12, 28, 58 oder 158 Mark in Frankfurt essen gehen kann. Dabei sind Fotografien in Frankfurter Lokalen, aber auch draußen entstanden, bei denen die beiden über die wichtigen Plätze der Stadt spazieren.",
            "Es gibt in Ihrem Film über die Handlungsstränge hinausgehende Szenen, die wie aus einem Dokumentarfilm hinzugeschnitten wirken: Ein Mann liegt mitten auf der Straße, neben ihm ein Krankenwagen mit Blaulicht, drumherum eine Menschentraube. Wie sind diese Bilder entstanden?",
            "Damals war es ja noch recht unkompliziert mit den Persönlichkeitsrechten. Wir haben bestimmte Szenen, wie diese, wo ein Schwerverwundeter mitten auf der Straße liegt und zu dem ein Krankenwagen fährt, inszeniert. Wir brauchten nur einen Statisten, der sich auf den Boden legt, einen Krankenwagen und zwei weitere Statisten standen vielleicht noch drumherum. Die Menschentraube entstand dann wie von selbst. Wir haben die Kamera mit einer gewissen Distanz postiert und das einfach aufgenommen. So vermengte sich Filmwelt und echte Welt.",
            "Zu Beginn Ihres Films kommt es zu einer heftigen Explosion in einem Billardsalon. Der von Hanno Pöschl gemimte kriminelle Zuhälter Johnny Klewer lässt bei einem Konkurrenten während dieser Billard spielt eine der Kugeln austauschen, die kurze Zeit später in die Luft gehen wird. Es blitzt hell auf, man sieht zerberstende Fensterscheiben im ersten Stock eines Gebäudes. Die Passanten auf der Straße scheinen es eher beiläufig wahrzunehmen, ohne Schock, ohne Entsetzen. Wie muss man sich so eine Film-Explosion vorstellen?",
            "Natürlich explodiert nicht die Billardkugel. Es handelt sich um einen technisch einfach zu bewerkstelligen Feuer-Effekt am Fenster. Sowas dauert nur zwei Sekunden und dann ist alles schon wieder vorbei. Ich glaube, wir hatten Gasflaschen dafür und dass Leute oben in der Wohnung standen, die zur gleichen Zeit etwas aus dem Fenster schmissen. Die Szene haben wir in einer Parallelstraße zur Kaiserstraße gedreht. Die Explosion war eine rein optische Sache und wurde erst im Nachhinein vertont, was wohl die relative Gleichgültigkeit der Passanten erklärt.",
            "War das mit der Billardkugel Ihre Idee?",
            "Ja, im Drehbuch war das so nicht festgeschrieben. Ich hatte das vorher irgendwo einmal gelesen. Man geht ja schließlich nicht einfach in einen Spielsalon und schmeißt eine Bombe. Aber laut Drehbuch sollte es genau so laufen.",
            "In einer weiteren, wunderbaren Szene, die das wortwörtlich genommene Versprechen der freimachenden Stadtluft ins Absurde führt, kommen sich Ihre beiden Hauptfiguren, das junge Liebespaar, im Gestrüpp direkt neben dem Frankfurter Autobahnkreuz näher, um schließlich entlang der Fahrbahn zu spazieren. War es einfach, von der Stadt für so einen Ort eine Drehgenehmigung zu erhalten?",
            "Wir sind dort einfach hingegangen, haben die Kamera aufgestellt, schnell gedreht und sind dann wieder weg. So einfach war das. Ich habe mir solche Sachen damals manchmal erlaubt. Die Polizei hätte sich sowieso kaum drum gekümmert. Die hätten gedacht: 'Ah, ne Kamera die da dreht, ah lass die mal.' Heute wäre das sicherlich viel schwieriger. Wahrscheinlich würden sofort drei Polizeiautos anrücken und nach Papieren verlangen. Als ich vor einiger Zeit hier in München im Englischen Garten Modefotos machen sollte, musste ich dafür extra eine Erlaubnis einholen und irgendwelche Gebühren entrichten. Mittlerweile werden ja für alles Gebühren erhoben. Das Klima in ganz Deutschland hat sich in dieser Richtung sehr verändert. Ein wachsender Staat – was vielleicht einfach damit zu erklären ist, dass es zu viele eitle Minister in all den Landesparlamenten gibt und jeder von denen unbedingt einen neuen Erlass verabschieden muss, damit sie auch nach ihrem Ausscheiden noch von Bedeutung sind. Das häuft sich in einer solchen Menge, dass am Schluss gar nichts mehr erlaubt sein wird, nicht einmal mehr der Erlass.",
            "In Ihrem Film selbst ist von einer staatlichen Ordnungsmacht weit und breit nichts zu sehen. Kein Verbrechen wird ermittelt, eine kriminelle Struktur allein durch eine andere ersetzt. Selbst auf eine moralische Einordnung wird abschließend verzichtet. Für am sonntäglichen 'Tatort' geschulte Augen harter Tobak. Wie kam das damals an?",
            "Die Polizei hat es dramaturgisch einfach nicht gebraucht. Und weil es Kriminalität immer geben wird, sie eine ständige Wiederholung ist, hat es mich nicht interessiert, sie im Film aufzulösen. Manchen Leuten war mein Film vielleicht zu realistisch. Die damals gewichtige katholische und evangelische Filmkritik störte sich sowieso an meinen Filmen, vor allem am Ausgang. Es fehlte ihnen die gerechte Strafe. Aber der Film war erfolgreich. Im Kino hat er seine Kosten locker eingespielt. Und auch im Fernsehen ist er dreimal gelaufen, was nochmals einen Haufen Geld einbrachte.",
            "Gab es eine Premierenfeier in Frankfurt, bei der Sie anwesend waren?",
            "Zu der kam es nicht. Der Cutter hatte den Film durch seinen Schnitt total verhunzt, so dass ich mit einem Mal ganz andere Probleme hatte. Ich musste den kompletten Film umschneiden. Der längst geplante Veröffentlichungstermin stand unmittelbar bevor, während ich mir nochmals die ganzen Negative habe kopieren lassen und wieder bei Null angefangen habe. Ich glaube sogar, dass bei der Uraufführung des Films noch der erste Schnitt lief, während ich weiterhin mit der Neufassung beschäftigt war.",
            "Drei Jahre vor Veröffentlichung Ihres Films drehte Fassbinder 'In einem Jahr mit 13 Monden'. Unmittelbar vor und nach Fassbinders Filmarbeit in Frankfurt waren Sie als Schauspieler an mehreren seiner Produktionen beteiligt. Zudem brachten Sie ein Fotobuch zu Fassbinders letztem Film 'Querelle' heraus. Haben Sie etwas von Fassbinders Frankfurt-Dreh mitbekommen, hat Sie sein Film vielleicht sogar beeinflusst? Und hat Fassbinder Ihren Film wiederum gesehen?",
            "Ich habe immer meine eigenen Sachen gemacht und mich trotz meiner Beteiligungen nicht sehr um Fassbinders Arbeit gekümmert. Von seinem Frankfurter Film habe ich gar nichts mitbekommen. Meinen Film wird er auch nicht gesehen haben, da bin ich mir ziemlich sicher. Da blieb ihm gar keine Zeit für. Aber er hat mich sehr verehrt, weil ich Assistent bei Visconti war. 1982 hatte Fassbinder den Falco-Song 'Der Kommissar' kurz nach dessen Erscheinen zu einem Drehbuch ausgearbeitet, das er in den Hauptrollen mit Hanno Pöschl und mir besetzte. Dazu ist es dann durch seinen Tod nicht mehr gekommen. In meinem Frankfurter Film gibt es indirekt über zwei Schauspieler eine Verbindung zu Fassbinder, die beide seinem engeren Kreis angehörten: Isolde Barth, die die Sekretärin meines Ganoven Johnny spielt, und Kurt Raab, der den in eleganten Frauenkleidern steckenden schwulen Onkel der Hauptfigur Susanne spielt. Kurt Raabs Lili Marleen-Szene in meinem Film ist übrigens eine der erstaunlichsten Sachen, die er je gemacht hat, wie ich finde.",
            "Zudem gibt es einen fabelhaften Dialog zwischen dem von Kurt Raab gespielten Onkel Ossi und dessen Lebensgefährten, als dieser ihn fragt: 'Aber glaubst du, dass die Normalen kein Recht auf Liebe haben? Das sind doch auch Menschen, oder?' Eine noch heute eindrucksvolle Wendung.",
            "Wissen Sie, ich denke sehr frei über diese Dinge, ohne große Einschränkungen. Ich habe ja auch mit sehr vielen Leuten, die homosexuell waren, gearbeitet. Neben dem erwähnten Luchino Visconti, dem ich in Rom assistierte, lebte ich ebendort zusammen mit Helmut Berger. Auch habe ich für den Fotografen Herbert List gearbeitet. Ich erinnere mich noch gut daran, wie der Bruder meiner Mutter ihr einen Brief geschrieben hat, in dem stand: Stell Dir mal vor, Dein Junge arbeitet bei einem schwulen italienischen Regisseur!",
            "Der Untertitel Ihres Films lautet: Eine Stadt als Nachtasyl. Wo fanden Sie nachts Asyl in Frankfurt?",
            "Da gab es den Gerhard Schüler, der das 'Plastik' und diese ganzen Kneipen hatte. Er war ein Freund von mir aus Mannheim. In meiner freien Zeit bin ich immer nur in seine Lokale gegangen. Er hat ja auch das 'Dorian Gray' im Frankfurter Flughafen gegründet. 1978 war ich bei dessen Eröffnung. Damals sind wir aus München eigens mit einem Sonderzug angereist, der direkt in den Flughafen einfuhr.",
            "Ihre weibliche Hauptfigur kellnert zeitweise in einem aberwitzigen, damals tatsächlich existierenden Außenlokal namens Bierwiese, einer Art Eckbrachen-Biergarten, wo ein Gast sie mit der zeitgemäßen, man würde heute sagen, Pick-Up-Line konfrontiert: 'Bring mir mal eine Bockwurst, die so knackig ist wie du.' Sie kontert trocken: 'Wir haben nur Frankfurter!' Da ist im Kleinen präsent, was Ihren Film im Ganzen durchzieht: Er schildert das Machtverhältnis zwischen den Geschlechtern, bei dem die scheinbare Souveränität der Männer im Dialog fortwährend subtil gewendet wird. War ihr Film vielleicht zu doppelzüngig, äußerlich zu trivial, um in seiner Qualität als Autorenfilm Würdigung zu finden?",
            "Der Film ist zweifellos ein Autorenfilm. Dass er die diesbezügliche Wahrnehmung nicht erhalten hat, ist meiner Meinung nach schlichtweg der Tatsache geschuldet, dass er als Lisa-Film erschien. Aber mir war das herzlich egal. Es war zu der Zeit, als ich im Grunde in Italien gelebt habe. Letztlich habe ich mich mein ganzes Leben nicht für diese Vereinsmeierei und Einordnungen interessiert. Fragen Sie einmal Roland Klick, den ich für einen der wirklich guten Regisseure halte, der wird Ihnen gleiches sagen. Am Ende ist es das Problem der Leute, die auf solche Einordnungen viel geben und dadurch nicht die hintere Ebene des Films sehen können.",
            "'Frankfurt Kaiserstraße' war Ihr letzter Spielfilm, warum?",
            "Ich habe noch öfter über weitere Spielfilme nachgedacht. Bei mir liegen auch ein paar Drehbücher herum. Eines hatte ich gemeinsam mit Ulf Miehe verfasst. Einmal kam es sogar noch zum Dreh, während dem allerdings relativ schnell die Produktionsfirma pleite ging. Und dann hatte ich auf einmal zwei Lokale in München, die ich eigentlich gar nicht haben wollte."
        ]
    },
    timmulrichs: {
        id: "timmulrichs",
        person: "Timm Ulrichs",
        coordinates: {
            lng: 8.700000,
            lat: 50.100000
        },
        color: "rgb(160, 110, 230)",
        title: "«Sie schenkte mir Adornos 'Minima Moralia' mit ihrem Lippenabdruck auf dem Umschlag»",
        subtitle: "Der Künstler Timm Ulrichs über seine Kunst in Frankfurt und Frankfurt im Kontext seiner Kunst",
        tag: "Frankfurt als Kunststadt",
        intro: "Timm Ulrichs' Werk ist kaum zu überblicken. Anstatt einen unverwechselbaren Stil auszubilden, wechselt er ihn immerzu, findet zu immer neuen Ideen und bespielt dabei alle Disziplinen der Bildenden Kunst. Oft fand seine Konzeptkunst erfolgreiche Nachahmer. Nicht selten wurde er dabei verschwiegen. Als Documenta-Teilnehmer weiß Ulrichs bereits zu Lebzeiten um ein von ihm gestaltetes Grabmal auf der Kasseler Künstler-Nekropole. Seine Arbeit 'Versunkenes Dorf' wurde zum Kunst-am-Bau-Projekt der Münchner Allianzarena. Nackt lief er mit Blitzableiter bei Gewitter über ein Feld, mit Blindenbrille, Blindenstock und gelber Armbinde trug er ein Schild mit dem Schriftzug 'Ich kann keine Kunst mehr sehen!' – viele seiner inszenierten Bilder sind längst ikonisch. Im letzten Jahr erhielt der mittlerweile Achtzigjährige den Käthe-Kollwitz-Preis der Akademie der Künste Berlin für sein Lebenswerk. Die Stadt Frankfurt spielt dabei gerade zu Beginn seiner Karriere eine wichtige Rolle. Im Gespräch erzählt Timm Ulrichs von der Mainmetropole als zeitweiligem Umzugsziel, wo man Adornos 'Minima Moralia' für ihn küsste, Kunst in seine Haut ging und eine verdeckte Beschattung seiner Person an der Straßenbahnhaltestelle endete.",
        interviewContent: [
            "Nachdem Sie sich 1961 zum 'Ersten lebenden Kunstwerk' erklärten, wollten Sie sich 1965 im Rahmen der 'Juryfreien Kunstausstellung' in Berlin konsequenterweise selbst ausstellen. Doch wurde dies kurzerhand verboten. Ein Jahr später war es dann doch möglich, allerdings in Frankfurt. Wie kam es dazu?",
            "Das Verbot meiner Selbstausstellung griff damals das 'stern'-Magazin auf, und zur Illustration des Artikels schickte man einen Fotografen zu den Ausstellungshallen am Funkturm, wo wir heimlich im Depot ein Foto mit mir im Glaskasten machten. Dieses Bild fand über eine Presseagentur weltweite Verbreitung. Infolge dieser Publizität wurde auch die mittlerweile legendäre Frankfurter Produzentengalerie Patio auf mich aufmerksam und bot mir an, meine Aktion dort zu wiederholen. Diese Galerie war zu jenem Zeitpunkt einer der avanciertesten Orte für Kunst, nicht nur in Frankfurt, der große experimentelle Freiheit erlaubte; Stanley Brown beispielsweise, der Konzeptkünstler aus Amsterdam, präsentierte sich hier erstmals in der Bundesrepublik. Mich kontaktierte damals Walter Zimbrich, neben Mario Barahona, Walter Kroe, Dieter Wetzk und Horst BaerenzCao einer der Gründungsväter der Galerie, die sich in einem Hinterhof in Sachsenhausen befand. Ich erinnere mich noch gut an den Fußweg dorthin – über den von Max Beckmann im Bild festgehaltenen Eisernen Steg, von wo man über die rechts liegende Schifferstraße in den Hinterhof der Laubestraße 24 gelang. Fast auf den Tag genau ein Jahr nach dem Berliner Verbot fand dort dann meine Selbstausstellung statt. Sie verlief über fünf Abende, vom 1. bis zum 5. Juni 1966.",
            "Haben Sie auch noch Erinnerungen an die Ausstellungsabende?",
            "Ich erinnere mich, wie mir der Maler Werner Schreib Bonbons in die Glasvitrine warf; andere zogen Grimassen wie vorm Affengehege im Zoo. Ich aber habe mir nichts anmerken lassen, sondern saß stillschweigend da und habe gelesen. An der Wand hingen Dokumente aus meinem Leben: Geburtsurkunde, Impfschein, Röntgenbild, Wiegekarte, Blut- und Samenproben. Trotz ihrer kurzen Dauer und der unaufwendigen Inszenierung hatte die Schau eine erstaunliche Resonanz.",
            "Wie fiel diesmal die Berichterstattung aus?",
            "Der Theater-Papst Günther Rühle schrieb am 3. Juni im Feuilleton der F.A.Z. einen sehr wohlwollenden vierspaltigen Bericht, 'Timm stellt sich aus'; das 'Time Magazine' titelte 'Don‘t Feed the Sculpture'; meine Schwester schickte mir das 'Aloha Magazine' aus Hawaii, das ebenfalls ein Foto brachte; und das 'Sunday Bulletin' in Philadelphia veröffentlichte gar einen Cartoon zu meiner Frankfurter Ausstellung, der Vor- und Nachteile lebender Kunstwerke bei Haus- und Gartenarbeiten abwog. Man kann durchaus sagen: Das Thema ging um die Welt.",
            "Was war dieses Frankfurt damals für eine Stadt?",
            "Frankfurt galt ganz klar als das intellektuelle Zentrum der Bundesrepublik. Als ich 1966 mein Architekturstudium in Hannover abbrach und mich als Eisverkäufer, Bauzeichner und mit anderen Gelegenheitsjobs über Wasser hielt, habe ich tatsächlich mit dem Gedanken gespielt, nach Frankfurt zu ziehen. Zwar hatte ich auch West-Berlin im Kopf, wohin ich stets einige Kontakte hatte, jedoch war Berlin seinerzeit künstlerisch eine Realisten-Hochburg, für mich also weniger interessant. Natürlich waren auch Düsseldorf als führende Künstlerstadt und Köln als Hauptstadt des Kunsthandels bedenkenswert, aber mich reizte Frankfurt am meisten. Da war damals nämlich außerordentlich viel los: Neben der Galerie Patio gab es weitere Avantgarde-Galerien wie etwa die Galerie dato bzw. Galerie d, die Galerien von Ursula Lichter und Dorothea Loehr und die Studiogalerie der Goethe-Universität; Theodor W. Adorno und Max Horkheimer lehrten an deren Institut für Sozialforschung; und der Suhrkamp-Verlag hatte jüngst Walter Benjamin neu verlegt. Auch der Schriftsteller und Galerist Adam Seide hatte seine Tätigkeit von Hannover nach Frankfurt verlegt, an seiner Zeitschrift 'Der Egoist' bzw. 'Der neue Egoist' habe ich mehrmals mitgearbeitet. In der Frankfurter Studentenzeitung 'Diskus', dessen durch Karl Riha verantwortetes Feuilleton die damals experimentellsten Texte publizierte, konnte ich einige Male ganze Seiten gestalten: mit einem Totalkunst-Manifest, 'seriellen Formationen' und einer Kollektion von Kanaldeckeln. Zweimal habe ich gar mit eigenem Stand an der Buchmesse teilgenommen, 1969 und 1970. Zudem studierte meine Freundin Alwine L. bei Adorno, und sie schenkte mir dessen 'Minima Moralia', mit ihrem Lippenabdruck auf dem Umschlag. Sie hatte eine transparente Folie darübergeklebt, damit der Kuss nicht mit der Zeit sich verwischen möge. Oft war ich mit ihr im Club Voltaire, in dem auch Jürgen Krahl und Günter Amendt vom Sozialistischen Deutschen Studentenbund verkehrten. Schließlich blieb ich dann doch in Hannover, mit einem Zweitwohnsitz in Münster, als mir dort 1972 eine Professur angeboten wurde.",
            "Weil ein Kunstwerk üblicherweise signiert wird, haben Sie sich im Jahr 1971 als lebendes Kunstwerk vom Frankfurter Tätowierer Horst H. Streckenbach – Pionier und Ikone der deutschen Tattoo- und Piercing-Szene, der mit seiner Mamillen-Rekonstruktion sogar Einzug in die medizinische Literatur fand – dann auch tätowieren lassen.",
            "'Samy's Tattoo Studio', wie Streckenbach sein Atelier nannte, befand sich in der Kurt-Schumacher-Straße 2, wo ich es auf meinem Weg zur Galerie Patio entdeckte und alsbald seinen Inhaber kennen- und schätzen lernte. Als mich 1971 Georg Bussmann, der damalige Leiter des Frankfurter Kunstvereins, einlud, mich an seiner Veranstaltung zur Experimenta 4 zu beteiligen, schlug ich ihm drei Arbeiten vor, die auch allesamt realisiert werden konnten. Eine davon sollte eine öffentliche Tätowierung in den Räumen des Kunstvereins sein, wofür ich Streckenbach vorsah, der auch sofort zusagte. Am 3. Juni baute er für die Aktion eigens einen Tresen im Kunstverein auf, den er mit Referenzabbildungen bestückte, um einige seiner bisherigen Arbeiten und Motive vorzustellen. Es wurde eine eindrucksvolle Show und eine der ersten Verbindungen zwischen dem damals noch anrüchigen Metier des Tätowierens und Bildender Kunst. Das Tattoo selbst war allerdings recht schlicht: Es bestand allein aus der Signatur 'Timm Ulrichs 1940 –'. Das Enddatum blieb offen und soll zu gegebener Zeit nachgetragen werden.",
            "Um was handelte es sich bei den anderen beiden Arbeiten?",
            "Zum einen färbte ich mithilfe von speziellen Tabletten mehrere Tage lang meinen Urin in verschiedenen Farben (orange, rot, grün, blau) ein und stellte ihn im Kunstverein in Erlenmeyerkolben aus. Zudem sorgte ich in einer nahegelegen, stark frequentierten öffentlichen Toilette am Paulsplatz für Irritationen, wo ich mich immer wieder an das erhöhte Ende einer Urinalrinne stellte und mein Wasser ließ. Sukzessive wendeten sich mir die Köpfe der anderen Anwesenden zu. Ich habe natürlich so getan, als sei alles ganz normal. Zum anderen ließ ich mich von einer Frankfurter Detektei für einen Tag beschatten. In meiner Unbekümmertheit rief ich bei einem dem Branchenverzeichnis entnommenen Detektivbüro an und unterbreitete meinen Plan, eine Art Tagebuch zu erhalten, nicht aus eigener, subjektiver Sicht, wie üblich, sondern aus fremder, distanzierterer Sicht. Als Antwort bekam ich zu hören, man sei doch ein seriöses Unternehmen und für so einen Unfug nicht zu haben. Daraufhin wandte sich ein Vorstandsmitglied des Kunstvereins an ein anderes Büro in der Kaiserstraße und berichtete, seine Frau nehme es mit der ehelichen Treue wohl nicht so genau, habe womöglich etwas mit einem gewissen Herrn Ulrichs, der zurzeit im Hotel Gloria in der Münchener Straße logiere, und bat darum, diesen für einen Tag zu beschatten. Ich erinnere mich noch, wie ich an jenem Tag, dem 4. Juni 1971, aus dem Fenster meines Hotelzimmers blickte und auf der Straße einen wartenden Mann im Trenchcoat sah, wie man ihn aus schlechten Kriminalfilmen kennt. Ich ging also auf die Straße und weiter in Richtung Theaterplatz. Im späteren Protokoll ist zu lesen, dass ich mich offenbar verfolgt fühlte und mich öfter umdrehte – dabei habe ich nur nach meinem Verfolger geschaut, damit ich ihn nicht aus Versehen abschüttele. Genau das ist dann aber passiert. Auf dem Weg zum Kunstverein – der Mann in gebührendem Abstand immer hinterher – ist eine Straßenbahn an mir vorbeigefahren, und dabei habe ich den Detektiv aus den Augen verloren. Daraufhin habe ich ihn suchen müssen, ihn aber nicht mehr gefunden. In seinem Bericht hat er dann geschrieben, ich sei urplötzlich in die Straßenbahn gesprungen und ihm dadurch entwischt.",
            "Kommen wir nochmals zurück auf Horst Streckenbach. Wie war ihr Verhältnis zueinander? Ihre Wege kreuzten sich ja im Fortgang noch des Öfteren.",
            "Mich verband mit Samy über viele Jahre ein durchaus freundschaftliches Verhältnis. Schon in den frühen siebziger Jahren schrieb ich ihm ein Gutachten, das ihm bescheinigte, nicht Handwerker, sondern Künstler zu sein, wodurch er in eine günstigere Steuerklasse kam. Wenn ich in Frankfurt war, habe ich ihn gern besucht und auch mehrere Male eingeladen, seine Künste vorzuführen, einmal nach Münster, wo er an unserer Kunstakademie einen Vortrag hielt, ein anderes Mal 1975 in den Kunstverein Hannover, wo ich ihn engagierte, öffentlich Interessierte zu tätowieren, die sich ihre Motive selbst auswählen konnten. In dem Frankfurter Satire-Magazin 'pardon' erschien aufgrund meiner Vermittlung ein großer Artikel von Gerd Winkler, der Samy leider kurzfristig in Schwierigkeiten brachte: Auf einer der Abbildungen war ein ganzkörpertätowierter Geschäftsmann zu sehen, dessen Ruf dadurch erheblichen Schaden nahm und der Samy daraufhin verklagte. Letztlich lag die Verantwortung für die fehlende Unkenntlichmachung des Bildes allerdings bei der Zeitschrift. Einmal half mir Samy, eine Zielscheibe, die ich mir 1974 in Barcelona von einem Fremdenlegionär über dem Herzen hatte stechen lassen – wobei man eigentlich eher von 'reißen' sprechen müsste –, so gut es ging zu korrigieren. 1981 war ich dann nochmals mit einem Kamerateam in seinem Studio, um mir auf das rechte Augenlid 'The End' tätowieren zu lassen – ein Motiv, das bis heute gern publiziert wird und für mich mit zunehmender Todesnähe natürlich seine Aktualität behält. Ende der achtziger Jahre, als wir keinen Kontakt mehr miteinander hatten, wurde Streckenbach durch einen übelgesinnten Finanzbeamten steuerlich zurückgestuft, woraufhin er rund hunderttausend Mark an Steuern nachzahlen musste. Nachdem bereits zuvor seine Frau ermordet worden war, erlitt Samy einen Herzinfarkt, musste sein Studio schließen und ist 2001 verarmt gestorben.",
            "Erlauben Sie mir die buchstäblich trostlose Überleitung zum Frankfurt der Gegenwart. Vor wenigen Jahren ist die sogenannte Neue Frankfurter Altstadt fertiggestellt worden. Von Ihnen gibt es eine Arbeit mit dem Titel 'Rekonstruktionen' (1988/94), bei der Sie einen Blumentopf zuerst in viele Einzelteile zerschlagen und jedes einzelne Teil daraufhin in einen neuen Blumentopf eingearbeitet haben. Wie denken Sie in diesem Zusammenhang über die Frankfurter Rekonstruktionen?",
            "Da bin ich zwiegespalten. Ich verstehe die Trauer der Menschen um Dinge, um Bilder, um Gebäude, die während des Krieges zerstört wurden, den Verlust historischer, auch biografischer Werte. Ich denke an den Maler Karl Hofer, dessen Atelier ausgebombt wurde; nach dem Krieg hat er viele seiner verlorenen Bilder mithilfe von Fotos oder aus der Erinnerung neu gemalt. Manche Kritiker monierten, diese neu-alten Arbeiten seien zu glatt, hätten ihr experimentelles Stadium eingebüßt, es fehle die lebendige Auseinandersetzung im Bild, sie wirkten nur nachgepinselt. Ich aber kann Karl Hofer verstehen. Ich habe selbst einige meiner alten Arbeiten aufgekauft, um sie wieder 'aufzumöbeln', andere habe ich sogar rekonstruiert. In der Beantwortung Ihrer Frage bin ich also vergleichsweise großzügig; vielleicht wäre ich es weniger, wenn zeitgenössische Architektur besser wäre. Wenn ich sehe, was nach dem Krieg gebaut worden ist, kann ich nicht sagen, ich sei immer für das Neue. Ich bin gewiss für die Moderne, aber nicht, wenn sie zum Rezept verkommt; die wiederaufgebauten Städte haben leider an Lebensqualität nicht gewonnen. Da kann ich dem Frankfurter Kompromiss durchaus Positives abgewinnen. Bei meiner Arbeit 'Rekonstruktionen' ging es mir um die Frage, ob ich, wenn ich beispielsweise den Finger einer antiken Venus-Figur finde, die ganze Figur rekonstruieren darf. Wie viel Substanz muss vorhanden sein bzw. darf fehlen, um den 'Rest' zu ergänzen? Ein heutiger Restaurator wird im Regelfall immer so anstücken, dass man das Alt-Echte und das Neue unterscheiden kann und man die Bruchkante sieht. Dieses Zeigen der Zeitschichten scheint in Frankfurt zumindest bei der Kenntlichmachung wiederverwendeter alter Steine und Spolien und durch die auch vorhandenen Neuinterpretationen geschehen zu sein. Den Begriff des Authentischen muss man also nicht fetischisieren.",
            "Frankfurt ist die Stadt der Hochhäuser. Es gibt von Ihnen eine Arbeit zu San Gimignano (1983/86), dem 'mittelalterlichen Manhattan', bei der Sie sich mit den toskanischen Geschlechtertürmen beschäftigen. Sie haben Holztische umgedreht, so dass die Beine wie Geschlechtertürme fungieren, und rote Betonpflastersteine in Hausform beigestellt, um den Maßstab anzudeuten. Was halten Sie von der Bauform des Hochhauses?",
            "In San Gimignano gilt ja noch der menschliche Maßstab; da muss man den Kopf nicht in den Nacken legen, muss nicht durch Wolken gucken, sondern kann die Türme mit normalem Blick wahrnehmen und rein körperlich, ohne Aufzug ersteigen. Architektur ist ja keine reine Kunst, sondern immer auch gebunden an soziale Verantwortung. Die Bedürfnisse der Menschen, die in den Städten wohnen, sind in einem anderen Maßstab zu sehen als die Bedürfnisse einzelner Bauherren und Architekten. Zwischen diesen unterschiedlichen Bedürfnissen muss man immer einen Ausgleich finden. Während meines Architekturstudiums haben mich die ersten Hochhäuser in Chicago und New York durchaus fasziniert, aber immer nur als Solitäre, ebenso der Eiffelturm, dem man zugutehalten kann, dass er in seiner Form und Konstruktion einzigartig ist und eine signifizierende, eine Wahrzeichen-Funktion hat. In Frankfurt gefällt mir Helmut Jahns einem angespitzten Bleistift ähnelnder Messeturm ganz gut. Aber die meisten anderen Türme in Frankfurt imponieren mir weniger. Wenn es darum gehen sollte, Bauplatz zu sparen und Natur zu schonen, kann ich Hochhäusern generell etwas abgewinnen. Dienen sie vornehmlich zur Machtdemonstration, verlieren sie für mich erheblich an Bedeutung.",
            "In manchen der Türme haben die Banken eigene Kunstsammlungen. Sie selbst sind in der Sammlung der DZ-Bank mit Ihrer Fotoarbeit 'Blaues Wunder' und in der Sammlung der Deutschen Bank mit Ihren 'Landschafts-Epiphanien' vertreten. Um was geht es den Banken dabei?",
            "Die genauen Motive für Firmensammlungen kenne ich nicht. Geht es um die Mitarbeiter des Hauses, die man an ihrem Arbeitsplatz entzücken möchte? Es gäbe ja auch durchaus die Möglichkeit, dass sich Angestellte aus dem Fundus Bilder aussuchen dürfen und so die Arbeit leichter fällt. Städtische und staatliche Museen haben die Aufgabe, Kunst zu sammeln, zu erforschen und öffentlich zu zeigen; das gilt für private und mithin auch die Sammlungen von Banken nicht in gleicher Weise. Museen in Deutschland veräußern einmal erworbenes Gut auch nicht mehr; diese Zurückhaltung ist für Firmen und Privatsammler aber nicht verbindlich – davon profitieren die Auktionshäuser. Da ich Kunst nicht als Ware, sondern zum Erkenntnisgewinn, also für die Öffentlichkeit mache, damit die Werke gezeigt und diskutiert werden können, sage ich mir: Lieber verkaufe ich ein Werk für tausend Euro an ein Museum als für zehntausend an einen Privatsammler – leider aber haben die Museen zu wenig Geld.",
            "Im Jahr 2025 wird sich der Amtsantritt Ernst Mays als Frankfurter Stadtbaurat und damit der Beginn des Neuen Frankfurt zum hundertsten Mal jähren. Die Resonanz darauf wird weitaus schwächer ausfallen, als dies 2019 beim Bauhaus-Jubiläum der Fall war. Anstelle vermeintlich objektiver Gründe scheint dies vor allem mit Walter Gropius‘ Geschick erklärbar, das Bauhaus nach seiner Emigration in die USA zu einer Marke ausgebaut zu haben, was Ernst May, der mit Teilen seines Frankfurter Mitarbeiterstabs in die Sowjetunion ging, so nicht möglich war. Lässt sich das Schicksal des Neuen Frankfurt mit dem Ihren vergleichen?",
            "Geschichtsschreibung ist ja ein Kapitel für sich. Wer hat das Recht zu entscheiden? Ich habe immer angekündigt, meine Strategie sei, die Kritiker und Kunsthistoriker, alle Besserwisser zu überleben und dann die Kunstgeschichte zu meinen Gunsten umzuschreiben. In manchen Fällen hat das sogar schon geklappt. Schauen Sie: Von Udo Kultermann gibt es das Buch mit dem Titel 'Leben und Kunst. Zur Funktion der Intermedia' (1970), in dem sich eine Liste mit Selbstausstellern findet. Ein Dutzend Namen ist dabei, aber meiner, der erste, fehlt. Es ist tatsächlich oft eine Machtfrage, ob man seinen Stellenwert zugebilligt bekommt oder nicht. Mittlerweile ist Kultermann tot, und ich kann für eine Korrektur sorgen. Von Ernst May habe ich übrigens als Architekturstudent an der Technischen Hochschule Hannover einen Vortrag gehört und mir von ihm ein Autogramm geben lassen, aus purer Verehrung. Wenngleich auch nicht so berühmt wie Gropius, Mies van der Rohe oder Corbusier, war er für mich doch ein großer Mann.",
            "Fällt Ihnen zum Abschluss noch eine kleine Anekdote ein, die Sie mit Frankfurt verbindet?",
            "Im Frankfurter Kunstverein gab es im Vorstand einen Werbegrafiker, der mir einen meiner 'Sitzenden Stühle' abkaufte. Später schrieb er mir, dass Diebe in seine Wohnung eingestiegen seien. Die Frankfurter Polizei habe in ihrem Protokoll nicht nur aufgelistet, was alles gestohlen worden sei, sie erwähnte auch einen demolierten Stuhl, dem die Hinterbeine gebrochen worden seien."
        ]
    },
    udonieper: {
        id: "udonieper",
        person: "Udo Nieper",
        coordinates: {
            lng: 8.720000,
            lat: 50.120000
        },
        color: "rgb(14, 120, 90)",
        title: "Mein Frankfurter U-Bahnhof funktioniert wie das Atomium",
        subtitle: "Der Architekt Udo Nieper über seinen Frankfurter U-Bahnhof 'Bockenheimer Warte'",
        tag: "Unterirdisches Frankfurt",
        intro: "Udo Nieper hat sich in den vergangenen Jahrzehnten als Architekt den unterschiedlichsten Bauaufgaben gestellt. Immer mit dem Ziel, Gelegenheiten zu schaffen statt Begebenheiten, wie er sagt. 1943 in Kiel geboren, studierte er an den Technischen Universitäten Berlin und Darmstadt, wo er 1970 bereits sein eigenes Büro gründete und zudem für ein Jahrzehnt als Dozent tätig war. In Frankfurt ist vor allem sein Wirken in den 1980er Jahren hervorzuheben: Er baute den U-Bahnhof 'Bockenheimer Warte', das in Architektenkreisen vielbeachtete Jugendzentrum am Bügel und war mitverantwortlich für den Umbau der Zeil zur Fußgängerzone. Im Gespräch erzählt Udo Nieper von seiner U-Bahn-Station als Tropfsteinhöhle, in deren Weiterführung Dinosaurier hätten einziehen sollen und erklärt, warum er trotzdem nur sehr bedingt ein Postmoderner war. Schon damals bedrückte ihn, was der Zeitgeist erst heute zu begreifen beginnt: Die Stadt sollte den Kindern kein Busbahnhof sein.",
        interviewContent: [
            "Mit Ihrer 1986 fertiggestellten U-Bahn-Station 'Bockenheimer Warte' der Linien U6 und U7 haben Sie eine der herausragendsten unterirdischen Stationen Frankfurts geschaffen. Sie mussten sich damals gegen das Frankfurter U-Bahn-Urgestein, den Architekten A.C. Walter durchsetzen, den Schöpfer der ersten und in Folge zahlreicher weiterer Stationen in Frankfurt. Für Sie als noch jungen Architekten war es der erste Stationsbau. Wie ist Ihnen das gelungen?",
            "Das war ein harter Kampf. Die Station 'Bockenheimer Warte' war Teil eines ausgelobten Wettbewerbs, der auch die zu bauenden Stationen 'Westend' und 'Alte Oper' umfasste. Eigentlich sollten alle drei Stationen von ein und demselben Architekten ausgeführt werden. A.C. Walter, der auch diesen Wettbewerb gewann, hielt sich bei seinem Entwurf zur Bockenheimer Warte allerdings nicht an die Vorgabe, ein unterirdisches Depot für die Zentralbibliothek mit einzuarbeiten. Architektonisch kann ich ihn sogar nachvollziehen: Ohne die in großem Umfang verlangten Magazinräume direkt unter der Erdoberfläche konnte er eine sehr viel höhere Bahnsteighalle planen. Weil ich die Vorgaben wiederum erfüllte, entschied das zuständige Stadtbahn-Bauamt, wie es damals noch hieß, den Auftrag doch aufzuteilen und mich mit dem Bau der U-Bahn-Station 'Bockenheimer Warte' zu beauftragen. A.C. Walter wollte das natürlich so nicht hinnehmen. So bekam ich eines Tages einen Brief des Bundes Deutscher Architekten, in dem sinngemäß stand, es sei eine Unverschämtheit, dass ich dem A.C. Walter einen Bahnhof wegnähme. Das brachte mich wiederum dazu, dem BDA meinerseits mit einer Beschwerde zu antworten. Ich reagierte wie ein bissiger Hund und fragte unverfroren, warum nicht ich alle drei Stationen bekäme. Denn mit meinen drei Entwürfen seien schließlich alle Anforderungen erfüllt. Der BDA zog seine Beschwerde schließlich zurück und ich konnte meine Station bauen.",      
            "Ihre Station erscheint auf der Verteilerebene wie ein riesiger Säulenwald. Große Spiegelflächen verstärken den Eindruck räumlicher Weite. Auch entlang des Bahnsteigs erstrecken sich zahlreiche Säulen. Rund 65 Säulen und Halbsäulen sind insgesamt zu zählen. Wozu all diese Säulen, wenn doch die meisten keinerlei tragende Funktion haben?",
            "In der Tat: Baulich-statisch war es bereits möglich, weitgehend ohne Stützen auszukommen. Es war damals sogar ausdrücklich erwünscht, auf sie weitestgehend zu verzichten, um das Sicherheitsgefühl der Passagiere zu stärken. Denn so brauchte man keine Angst davor haben, hinter einer Säule könnte sich jemand verstecken. Was das angeht, war mein Entwurf vollkommen widersinnig. Ich habe allerdings räumlich gedacht: Eine U-Bahn-Station liegt unterirdisch; betritt man sie, geht man im Prinzip in eine Höhle. Wenn ich nun eine Ebene habe, die riesengroß ist, bei einer Deckenhöhe von vielleicht drei Meter fünfzig, wirkt diese bedrückend niedrig. In dem Moment aber, in dem ich Vertikalen schaffe, ändert sich das Raumempfinden schlagartig. Denken Sie an eine Tropfsteinhöhle: Zwischen den Stalaktiten und Stalagmiten wirken die kleinen Räume ziemlich hoch. Um also ein anderes Raumgefühl zu bekommen, füllte ich meine Station mit zig Säulen in unterschiedlichen Breiten, wie auch Stalaktiten und Stalagmiten von verschiedenem Durchmesser sind. Das durchzubekommen, gegen das erklärte Sicherheitskonzept der Stadt, war natürlich wieder ein Kampf. Zuerst stellte man sich quer. Mir half schließlich mein gebautes Modell, in das man von oben mithilfe eines Periskops reinschauen konnte, um die Station aus Perspektive der Fußgänger zu betrachten. Graphische Darstellungen wie heute waren damals noch nicht möglich. Da standen sie vom Stadtbauamt dann alle in einem großen Saal um das kleine Modell eng beieinander, schauten nacheinander in das Sehrohr und sagten: Das sieht aber schön aus!",
            "Den optischen Mittelpunkt Ihrer 'Tropfsteinhöhle' bildet eine wuchtige Säule mit einer zweieinhalb mal zweieinhalb Meter großen und 550 Kilo schweren, aus Bronze gegossenen Nachbildung eines Sofakissens. An seinen Ecken weist es große Außenwulste auf, so als quetsche die Last der Decke die Polsterung zur Seite. Ein architektonischer Witz?",
            "Ja. Das Kissen spielt auf das klassische Kapitell mit seinen Voluten an, wie wir es aus der Architekturgeschichte kennen. Der Bildhauer Richard Heß hatte hierzu die Idee, die mir auf Anhieb gefiel, so dass ich ihn beim Stadtbauamt für die Ausführung vorschlug. Von ihm stammt übrigens auch die Skulptur 'David und Goliath' auf der von Walter Rolfes, Dietrich Bangert und mir bis 1985 umgebauten Zeil. Die große Säule mit der Kissenskulptur sollte aber nicht nur unterhalten, sondern vor allem Orientierung ermöglichen – in einer ansonsten unendlich scheinenden Höhle.",
            "Ist denn zumindest diese Säule tragend?",
            "Ja, aber natürlich auch noch einige, wenige andere.",
            "Einen weiteren 'Witz' Ihres U-Bahnhofs, wenn ich das so formulieren kann, liefert ein Eingang des Architekten und Künstlers Peter Pininski: Die Nachbildung eines alten Straßenbahnwaggons, der schräg in den Erdboden eingelassen ist und so den Weg in den Untergrund ebnet. Etwa die Hälfte des Wagons liegt frei, drumherum Geröll und durchbrochenes Straßenpflaster. Der Architekturkritiker Dieter Bartetzko sah in diesem 'unfreiwillig [ein] Triumphmal städteplanerischer Ignoranz', wie er es in der Frankfurter Studentenzeitschrift Diskus formulierte. So stand der Bau Ihrer Station als Teil der sogenannten C-Linie im Zusammenhang mit dem Verkehrskonzept 'Schienenfreie Innenstadt', gegen das sich großer Widerstand aus der Stadtbevölkerung formierte, der schließlich gar zur Absage der Eröffnungsfeierlichkeiten führte und die Inbetriebnahme um einige Woche hinauszögerte. Wie positionierten Sie sich in dieser Angelegenheit?",
            "Ich habe mich auf jeden Fall nicht unwohl gefühlt, weil ich eine U-Bahn-Station bauen durfte. Das Prinzip der U-Bahn bietet viele Vorteile. Aber auch ein oberirdisches Straßenbahnnetz ist absolut wichtig und richtig. Ich denke, man sollte beide Systeme nicht gegeneinander ausspielen, sondern sie als gegenseitige Ergänzung zusammendenken.",
            "Weitere Besonderheiten Ihrer Station sind die großformatigen Schwarz-Weiß-Aufnahmen der Fotografin Barbara Klemm an den Bahnsteigwänden, die den universitären Alltag der 1980er Jahre zeigen, und Spiegel zwischen diesen, die teils wiederum von Halbsäulen unterteilt werden. Was hat es mit den Spiegeln auf sich? Stehen sie in einer bewussten Verbindung zu den Fotografien?",
            "Meine Überlegung war die Folgende: Wenn ich am Bahnsteig stehe, interessieren mich am meisten meine unmittelbaren Nachbarn. Ich kann sie aber nicht einfach so angucken. Manchmal möchte ich vielleicht auch mich sehen. Mithilfe der Spiegel ist es möglich, sich, vor allem aber die Anderen zu beobachten, ohne dabei gleich die Anstandsregeln zu verletzen. Die Fotografien wiederum sollten die Station natürlich im oberirdischen Kontext der Goethe-Universität verorten. Doch sollten die auf den Fotografien abgebildeten Personen darüber hinaus eigentlich alle im gleichen Maßstab wie die gespiegelten Passagieren sein, so dass daraus spannende Bild-Collagen entstanden wären, sich die auf die U-Bahn-Wartenden plötzlich selbst in den abgebildeten Szenerien der Universität wiedergefunden hätten. Barbara Klemm hat sich dann allerdings nicht an das Prinzip des gleichen Maßstabs gehalten. Sie hatte ihre eigenen Vorstellungen. Ihre Fotografien sind natürlich trotzdem toll. Auch die zur Verwendung gekommenen Spiegel waren letztlich nur Imitate aus Blech – aus Sorge vor Vandalismus. Der Spiegeleffekt fällt somit sehr viel schwächer aus. Aber das sind Kompromisse, die man als Architekt immer wieder eingehen muss.",
            "Das Bibliotheksleben ist aus der Station mittlerweile verschwunden. Lange Zeit gab es einen direkten, unterirdischen Zugang mit großem Foyer zum offenen Magazin der Zentralbibliothek, der mittlerweile geschlossen und von Vorhängen verdeckt ist. Auch gab es eine Bücherausleihe auf der Verteilerebene. Die mittlerweile meist leeren Glasvitrinen dienten zur Präsentation neuer Publikationen. Sind Sie wehmütig, wenn Sie heute durch Ihren U-Bahnhof gehen?",
            "Das was ich mache, wird verändert. So war es auch bei der Zeil, für die wir eine grüne Spange von der Ostzeil über die Konstablerwache bis hin zu Fressgasse bauen ließen. Mit dem späteren Umbau wurde die Anzahl der Bäume wieder reduziert, die Pavillons abgerissen, eine neue, fürchterliche Beleuchtung angebracht und auch die alten Sitzgelegenheiten mit ihren vier Segmenten, auf denen es immer wieder zu den wunderbarsten Begegnungen kam, wurden durch unmaßstäbliche Bänke ersetzt. Ich habe zuhause noch etliche Fotos, die zeigen, wie wohlsituierte Damen direkt neben Obdachlosen saßen. Immerhin ist die Baumidee geblieben, sogar zur Ortsidentität geworden. Aber selbst derer wollten sich manche Geschäftsleute und Stadtverordnete wieder entledigen. Ich entwarf zudem des öfteren Gebäude, bei denen schon während der Bauphase klar war, dass sie nach ihrer Vollendung nicht mehr gebraucht würden. Man sollte sich bei allem besser nicht so wichtig nehmen. Schon gar nicht für die Nachwelt bauen. Das wäre viel zu vermessen. Ich empfinde beim Gang durch meine Station keine Wehmut. Mich macht hingegen etwas ganz anderes traurig, oder besser: wütend. Für mich als Kind, 1943 geboren, war die Straße der öffentliche, der soziale Raum. Sie war mein Leben. Ich habe immer in Städten gelebt. Wenn ich meine Enkel heute frage, für was eine Straße da sei, antworten sie mir, damit Autos dort fahren und parken könnten. Den Verlust des sozialen Lebens in den Straßen der Städte durch die Verkehrswende der letzten Jahrzehnte will ich nicht hinnehmen. Schauen Sie, wie Kinder bis zu ihrem 10. Lebensjahr ihre städtische Umgebung wahrnehmen: Hohe Blechwände versperren ihnen die Sicht. Hässlicher, aber auch gefahrvoller geht es nicht. Das wäre für uns Erwachsene in etwa so, als wären die Straßen ein riesiger Busbahnhof. Wir könnten nichts mehr sehen. Der ruhende Verkehr muss aus den Städten verschwinden. Das umtreibt mich seit den 1980er Jahren. Jetzt ist die Zeit hoffentlich endlich reif dafür.",
            "Gibt es eine Haltung, die Ihren Entwürfen vorangeht und die Sie über die Jahrzehnte Ihres Wirkens beibehalten haben?",
            "Lassen Sie es mich so erklären. Ein anderes Frankfurter Architekturbüro sah für die Zeil beispielsweise ein Riesenrad als Dauerinstallation vor, Eintrittspreis 50 Pfennig. Die Leute sollten beschäftigt werden. Wir hingegen wollten die Leute in Ruhe lassen. Die Menschen sollen keine Begebenheiten vorfinden, die ihnen vorschreiben, was zu tun ist, sondern Gelegenheiten, um sich selbst zu entwickeln. Das war bei allem, was ich tat, mein Credo.",
            "Nochmals zurück zu Ihrer Station. Den zweiten, 2004 fertiggestellten und ebenfalls von Ihnen stammenden Teil der Linie U4 haben wir bisher ausgelassen. Dieser imponiert durch seine extrem hohe Bahnsteighalle, die bei der Fahrt hinunter mit dem gläsernen Lift eine nahezu sakrale Wirkung entfaltet. An den Bahnsteigen aus Sichtbeton sind weitere, jüngere Schwarz-Weiß-Aufnahmen des akademischen Betriebs angebracht, weiterhin farbige Abbildungen aus der Tier- und Pflanzenwelt, die auf das in unmittelbarer Nachbarschaft liegende Naturkundemuseum Senckenberg und den ebenfalls nahegelegenen Palmengarten verweisen. Spiegelflächen hingegen oder gar weitere Kunst am Bau sind nicht zu entdecken. Einzig auf ihre wuchtige Säule spielen Sie durch eine ebenso große, allerdings nüchtern gehaltene Säule an, die in einer Eingangs-Rotunde steht. Ist es ein bewusster Verzicht auf weitere Pointen?",
            "Meine Losung beim zweiten Bauabschnitt war tatsächlich erst einmal 'So hoch wie möglich!' Das, was mir beim ersten Bauabschnitt durch die unterhalb des Bahnsteigs nötigen Buchlagerräume nicht möglich war, wollte ich nun umso nachdrücklicher erreichen, auch wenn hohe unterirdische Räume für die Statiker immer ein Problem sind. Es brauchte Bodenplatten von zwei Meter Dicke, um das fehlende Gewicht der entnommenen Erde zu ersetzen. Beton als noch schwerere Erde sozusagen. Doch damit nicht genug. Eigentlich wollte ich die hohe Bahnsteighalle bis zum Senckenbergmuseum fortsetzen, um dort die großen Dinosaurier hinzustellen. Durch die offene Bauweise hätte man das durchaus bauen können. Aber es wäre natürlich teurer geworden, weshalb man schließlich alles wieder mit Erde zudeckte. An dieser Stelle also, bei der Einbeziehung der Dinosaurier in das Stationsleben, habe ich mich leider nicht durchsetzen können.",
            "Hans Haverkampf, damaliger Baudezernent Frankfurts, sagte über den von Ihnen mit verantworteten Umbau der Zeil: 'Vielleicht ist die Zeil Deutschlands erste postmoderne Fußgängerzone.' Dieter Bartezko schrieb über Ihre U-Bahn-Station: 'Und sei es wider Willen: Mit diesen unterirdischen Spiegelkabinen, dieser zersplitterten Welt, in der Geschichte und Gegenwart, Tempel und Fabrik, Maschine und Säule, Vergnügungen und Verwirrung drunter und drüber geraten sind, ist ein Inbegriff postmoderner (Bau)Welt geschaffen.' Hatten Sie damals das Bewusstsein: 'Ich baue postmodern!'?",
            "Natürlich gibt es so etwas wie Zeitgeist, der einen sicherlich auch irgendwo beeinflusst. Allein durch die ganzen Architekturzeitschriften war ich im Bilde. In einem bestimmten Milieu wollte ich mich aber nicht bewegen. In ersten Linie war ich Architekt, der sich konkreten Bauaufgaben stellt – mit Vorliebe für das gestalterische Detail, Schönheit. Nehmen Sie die goldenen Kanneluren an meinen Säulen. Ihr Grund ist letztlich ganz banal: Damit man die Säulen nicht so leicht besprühen kann. Sie waren nicht als Zitat gemeint. Natürlich hätte ich die Säulen auch befliesen können, aber das sähe dann eben weniger schön aus. Ich möchte es nochmals mit meinem ebenfalls 1985 fertiggestellten Jugendzentrum am Bügel in Frankfurt erklären, das damals für ziemliche Furore sorgte und bundesweite Wertschätzung erfuhr. Am Anfang stand nicht die Idee, ich baue postmodern, sondern ich habe radikal aus Sicht der Kinder und Jugendlichen gedacht, mit dem Ziel, diesen Architektur zu vermitteln. In dem Bau habe ich alles untergebracht: einen gemütlichen Kaminbau im Stile einer Skihütte, ein Reihenhaus für die einzelnen Räume, eine Werkstatt, ein Clubraum und eine Disko, ein nach allen Seiten offenes Industriedach, das die verschiedenen Baukörper zu einer Einheit zusammenfasst, zuletzt eine Betonmauer drumherum mit Segmenten aus Glasbausteinen. Ich baute ein Sammelsurium architektonischer Eindrücken – im Sinne der Kinder, nicht der Postmoderne.",
            "Abschließend möchte ich Sie fragen: Mögen Sie das unterirdische Frankfurt?",
            "Die vielen Wettbewerbe, die man in Frankfurt ausgerichtet hat, haben der Stadt auf jeden Fall viele tolle Stationen beschert. Das unterscheidet Frankfurt von anderen Großstädten, wo man sich dem Stationsbau allein bauingenieurmäßig angenommen hat, bloß danach fragte, wie man möglichst billig und ohne Hindernisse von A nach B kommt. Dort bestehen die Stationen aus bloßen Gängen. Architekten aber haben ein räumliches Gefühl. Ich dachte immer in Etappen, von Zentralraum zu Zentralraum, um lange Gänge zu vermeiden. Mein Frankfurter U-Bahnhof funktioniert wie das Atomium, wo die verschiedenen Erlebnisräume durch kurze Gänge miteinander verbunden sind. Mir gefallen im Übrigen auch die beiden Stationen von A.C. Walter, 'Westend' und 'Alte Oper', über die wir zu Beginn gesprochen haben. Nur sein sogenanntes Loch an der Hauptwache ist eine einzige Katastrophe."
        ]
    },
    test3: {
        color: "rgb(140, 80, 20)",
        tag: "Udo Nieper",
        subtitle: "Mein Frankfurter U-Bahnhof funktioniert wie das Atomium"
    },
    test4: {
        color: "rgb(240, 190, 60)",
        tag: "Udo Nieper",
        subtitle: "Mein Frankfurter U-Bahnhof funktioniert wie das Atomium"
    },
    test5: {
        color: "rgb(40, 120, 180)",
        tag: "Udo Nieper",
        subtitle: "Mein Frankfurter U-Bahnhof funktioniert wie das Atomium"
    },
    test6: {
        color: "rgb(90, 120, 200)",
        tag: "Udo Nieper",
        subtitle: "Mein Frankfurter U-Bahnhof funktioniert wie das Atomium"
    },
    test7: {
        color: "rgb(30, 200, 100)",
        tag: "Udo Nieper",
        subtitle: "Mein Frankfurter U-Bahnhof funktioniert wie das Atomium"
    },
    test8: {
        color: "rgb(210, 160, 40)",
        tag: "Udo Nieper",
        subtitle: "Mein Frankfurter U-Bahnhof funktioniert wie das Atomium"
    },
};

module.exports = { interviews }





