const interviews = [
    {
        id: "rogerfritz",
        title: "Wir sind dort einfach hingegangen, haben die Kamera aufgestellt, schnell gedreht und sind dann wieder weg",
        subtitle: "Der Regisseur Roger Fritz über seinen Film 'Frankfurt Kaiserstraße'",
        tag: "Frankfurt als Nachtasyl",
        intro: "1981 erscheint mit 'Frankfurt Kaiserstraße' ein Film von Roger Fritz, der damals als Milieustudie so raffiniert war, wie er heute als dokumentarische Zeitkapsel funktioniert. Wenngleich das Frankfurter Bahnhofsviertel vordergründig als Schablone dient, um die Figuren im sumpfigen Zwielicht lernen zu lassen, dass es die ersehnte Freiheit bloß im sich widerstreitenden Plural gibt, gelingt ihm doch zugleich ein Porträt dieses großstädtischsten aller Frankfurter Stadtviertel, seiner Straßenzüge, Etablissements, Kleidermoden und Sprechweisen. Der 1936 geborene Roger Fritz ist nicht nur Regisseur mehrerer Filme und zahlreicher Fernsehserien, sondern ebenso ausgebildeter Schauspieler und vor allem Fotograf. Er assistierte Luchino Visconti bei 'Boccaccio 70' und 'Il Gattopardo', arbeitete für Gian Carlo Menotti in New York, spielte bei Fassbinder und fotografierte Andy Warhol, Romy Schneider oder die Beatles. Im Gespräch schildert er seine Drehstrategie, die von einer zurückhaltenden Polizei profitierte, berichtet von einem gewonnenen Rückwärtsautorennen in Frankfurt, wo das Filmmuseum seinen Film später nicht zeigen wollte und erklärt, warum er 'Frankfurt Kaiserstraße' lieber in Hamburg gedreht hätte.",
        interview: [
            "Nachdem Sie Ende der 1960er Jahre gleich drei Spielfilme drehten, traten Sie als Regisseur in den Folgejahren allein mit Fernsehserien in Erscheinung. Erst 1981 kam mit 'Frankfurt Kaiserstraße' ein weiterer Film von Ihnen in die Kinos. Was brauchte es, damit Sie sich wieder zu einem Spielfilm durchringen konnten?",
            "Ich habe mich nicht durchgerungen. Das funktioniert beim Film so nicht. Ein Film kostet ein Schweinegeld, da braucht es immer jemanden, der ihn finanziert. Dass ich über zehn Jahre keinen Spielfilm mehr gedreht habe, hing bestimmt auch damit zusammen, dass ich meine vorherigen Filme allesamt selbst produzierte. Vor so jemandem haben andere Verleiher einen Riesen-Respekt. In dem konkreten Fall kam dann Karl Spiehs von Lisa-Film auf mich zu und fragte, ob ich 'Frankfurt Kaiserstraße' machen will. Das Drehbuch lag vor und auch die Rollen waren bereits besetzt.",      
            "Lisa-Film produzierte für den Massenmarkt, hauptsächlich leicht verdauliche Komödien und Erotikfilme. Wie passte Ihr Film in dieses Portfolio?",
            "Die haben sich da sicherlich etwas ganz anderes drunter vorgestellt als das, was nachher aus dem Film geworden ist. Es war nicht leicht, den Film zu drehen. Ich hatte mit vielen Widerständen zu kämpfen. Das fing schon damit an, dass ich entgegen der eigentlichen Besetzung den Wiener Schauspieler Hanno Pöschl dazu holte. Wobei ich das immerhin noch vermitteln konnte, weil Lisa-Film schließlich eine deutsch-österreichische Produktion war. Aber auch die Rollen der beiden Hauptfiguren Susanne und Rolf habe ich neu besetzt. Den männlichen Part sollte eigentlich Heiner Lauterbach spielen, der mir für die Rolle zu erwachsen war. Ich entschied mich für das Modell Michaela Karger und den Musiker Dave Balko, die mit Schauspielerei rein gar nichts am Hut hatten und danach auch nicht mehr als Schauspieler in Erscheinung getreten sind. Darüber hinaus habe ich noch während des Drehs fast alles am Drehbuch und dessen Texten verändert.",
            "War es Ihre Entscheidung, in Frankfurt zu drehen?",
            "Das lag schlichtweg daran, dass das Drehbuch, das bereits existierte, in Frankfurt spielte. Wenn ich Einfluss auf den Drehort hätte nehmen können, wäre mein Film wohl in Hamburg auf St.Pauli entstanden. Denn St. Pauli kannte ich in- und auswendig, dort hatte ich für verschiedene Serien gearbeitet. Klar wurde damals von Frankfurt als dem 'deutschen Chicago' gesprochen, aber das war doch ziemlicher Quatsch. Immerhin lieferte das Bahnhofsviertel um die Kaiserstraße die Kulisse dafür. Und mir kam zugute, dass ich jemanden aus der Frankfurter Unterwelt kannte, so dass ich in den entsprechenden Lokalitäten drehen konnte.",
            "Welche Verbindung hatten Sie ansonsten in die Mainmetropole?",
            "Obwohl ich aus Mannheim bin, hatte ich biographisch zu Frankfurt keine große Beziehung. Ich war nie für eine längere Zeit in der Stadt, sondern immer nur ganz gezielt im Rahmen irgendwelcher Veranstaltungen. Ich habe in Frankfurt mal mit einem Alfa Romeo ein Rückwärtsautorennen gewonnen, für das ganz offiziell eine Straße abgesperrt wurde. Das war noch ein paar Jahre bevor ich den Film drehte. Später wiederum gab es im Filmmuseum am Mainufer mal eine Ausstellung über mich, in deren Rahmen auch meine Filme gezeigt werden sollten. 'Frankfurt Kaiserstraße' fanden sie so beschissen, dass sie ihn einfach weggelassen haben.",
            "Und Sie, wie finden Sie Ihren Film?",
            "Als der Film fertig war, war ich nicht so begeistert. Erst später begann ich den Film zu mögen.",
            "Eine Qualität Ihres Film ist zweifellos seine nahbare, sehr direkte Bildsprache, die zugleich sehr komponiert wirkt. Er arrangiert die Straßenzüge und Etablissements der zwielichtigen Lebenswelten so ausführlich und direkt wie ein Dokumentarfilm und ist doch so ästhetisch wie es nur ein Spielfilm sein konnte.",
            "Bevor ich in Berlin auf die Ufa-Nachwuchsschule ging, war ich schon ein verhältnismäßig bekannter Fotograf. Die Fotografie hat mich bei meiner Filmarbeit von Beginn an sehr beeinflusst. 'Frankfurt Kaiserstraße' profitiert sicherlich auch von meinen vorherigen Fotoreportagen über das Rotlicht. Von der Fotografie kommend entstand für mich ein ganz anderer innerer Aufbau als bei jemandem, der nur von der Sprache und der Regie her denkt. Wenn ich in einen Raum komme, sehe ich die Szene bereits, sehe, wo sie spielt. Wahrscheinlich sind meine Filme deshalb auch ein bisschen realer als die der anderen Jungfilmer zu jener Zeit. Einen Kameramann hätte ich deshalb eigentlich gar nicht gebraucht, sondern bloß einen Assistenten.",
            "Hatten Sie auch in Frankfurt zuvor einmal fotografiert?",
            "Für das von mir mitgegründete Twen-Magazin habe ich mal eine Reportage mit zwei jungen Leuten gemacht, die zeigt, wie man für 5, 12, 28, 58 oder 158 Mark in Frankfurt essen gehen kann. Dabei sind Fotografien in Frankfurter Lokalen, aber auch draußen entstanden, bei denen die beiden über die wichtigen Plätze der Stadt spazieren.",
            "Es gibt in Ihrem Film über die Handlungsstränge hinausgehende Szenen, die wie aus einem Dokumentarfilm hinzugeschnitten wirken: Ein Mann liegt mitten auf der Straße, neben ihm ein Krankenwagen mit Blaulicht, drumherum eine Menschentraube. Wie sind diese Bilder entstanden?",
            "Damals war es ja noch recht unkompliziert mit den Persönlichkeitsrechten. Wir haben bestimmte Szenen, wie diese, wo ein Schwerverwundeter mitten auf der Straße liegt und zu dem ein Krankenwagen fährt, inszeniert. Wir brauchten nur einen Statisten, der sich auf den Boden legt, einen Krankenwagen und zwei weitere Statisten standen vielleicht noch drumherum. Die Menschentraube entstand dann wie von selbst. Wir haben die Kamera mit einer gewissen Distanz postiert und das einfach aufgenommen. So vermengte sich Filmwelt und echte Welt.",
            "Zu Beginn Ihres Films kommt es zu einer heftigen Explosion in einem Billardsalon. Der von Hanno Pöschl gemimte kriminelle Zuhälter Johnny Klewer lässt bei einem Konkurrenten während dieser Billard spielt eine der Kugeln austauschen, die kurze Zeit später in die Luft gehen wird. Es blitzt hell auf, man sieht zerberstende Fensterscheiben im ersten Stock eines Gebäudes. Die Passanten auf der Straße scheinen es eher beiläufig wahrzunehmen, ohne Schock, ohne Entsetzen. Wie muss man sich so eine Film-Explosion vorstellen?",
            "Natürlich explodiert nicht die Billardkugel. Es handelt sich um einen technisch einfach zu bewerkstelligen Feuer-Effekt am Fenster. Sowas dauert nur zwei Sekunden und dann ist alles schon wieder vorbei. Ich glaube, wir hatten Gasflaschen dafür und dass Leute oben in der Wohnung standen, die zur gleichen Zeit etwas aus dem Fenster schmissen. Die Szene haben wir in einer Parallelstraße zur Kaiserstraße gedreht. Die Explosion war eine rein optische Sache und wurde erst im Nachhinein vertont, was wohl die relative Gleichgültigkeit der Passanten erklärt.",
            "War das mit der Billardkugel Ihre Idee?",
            "Ja, im Drehbuch war das so nicht festgeschrieben. Ich hatte das vorher irgendwo einmal gelesen. Man geht ja schließlich nicht einfach in einen Spielsalon und schmeißt eine Bombe. Aber laut Drehbuch sollte es genau so laufen.",
            "In einer weiteren, wunderbaren Szene, die das wortwörtlich genommene Versprechen der freimachenden Stadtluft ins Absurde führt, kommen sich Ihre beiden Hauptfiguren, das junge Liebespaar, im Gestrüpp direkt neben dem Frankfurter Autobahnkreuz näher, um schließlich entlang der Fahrbahn zu spazieren. War es einfach, von der Stadt für so einen Ort eine Drehgenehmigung zu erhalten?",
            "Wir sind dort einfach hingegangen, haben die Kamera aufgestellt, schnell gedreht und sind dann wieder weg. So einfach war das. Ich habe mir solche Sachen damals manchmal erlaubt. Die Polizei hätte sich sowieso kaum drum gekümmert. Die hätten gedacht: 'Ah, ne Kamera die da dreht, ah lass die mal.' Heute wäre das sicherlich viel schwieriger. Wahrscheinlich würden sofort drei Polizeiautos anrücken und nach Papieren verlangen. Als ich vor einiger Zeit hier in München im Englischen Garten Modefotos machen sollte, musste ich dafür extra eine Erlaubnis einholen und irgendwelche Gebühren entrichten. Mittlerweile werden ja für alles Gebühren erhoben. Das Klima in ganz Deutschland hat sich in dieser Richtung sehr verändert. Ein wachsender Staat – was vielleicht einfach damit zu erklären ist, dass es zu viele eitle Minister in all den Landesparlamenten gibt und jeder von denen unbedingt einen neuen Erlass verabschieden muss, damit sie auch nach ihrem Ausscheiden noch von Bedeutung sind. Das häuft sich in einer solchen Menge, dass am Schluss gar nichts mehr erlaubt sein wird, nicht einmal mehr der Erlass.",
            "In Ihrem Film selbst ist von einer staatlichen Ordnungsmacht weit und breit nichts zu sehen. Kein Verbrechen wird ermittelt, eine kriminelle Struktur allein durch eine andere ersetzt. Selbst auf eine moralische Einordnung wird abschließend verzichtet. Für am sonntäglichen 'Tatort' geschulte Augen harter Tobak. Wie kam das damals an?",
            "Die Polizei hat es dramaturgisch einfach nicht gebraucht. Und weil es Kriminalität immer geben wird, sie eine ständige Wiederholung ist, hat es mich nicht interessiert, sie im Film aufzulösen. Manchen Leuten war mein Film vielleicht zu realistisch. Die damals gewichtige katholische und evangelische Filmkritik störte sich sowieso an meinen Filmen, vor allem am Ausgang. Es fehlte ihnen die gerechte Strafe. Aber der Film war erfolgreich. Im Kino hat er seine Kosten locker eingespielt. Und auch im Fernsehen ist er dreimal gelaufen, was nochmals einen Haufen Geld einbrachte.",
            "Gab es eine Premierenfeier in Frankfurt, bei der Sie anwesend waren?",
            "Zu der kam es nicht. Der Cutter hatte den Film durch seinen Schnitt total verhunzt, so dass ich mit einem Mal ganz andere Probleme hatte. Ich musste den kompletten Film umschneiden. Der längst geplante Veröffentlichungstermin stand unmittelbar bevor, während ich mir nochmals die ganzen Negative habe kopieren lassen und wieder bei Null angefangen habe. Ich glaube sogar, dass bei der Uraufführung des Films noch der erste Schnitt lief, während ich weiterhin mit der Neufassung beschäftigt war.",
            "Drei Jahre vor Veröffentlichung Ihres Films drehte Fassbinder 'In einem Jahr mit 13 Monden'. Unmittelbar vor und nach Fassbinders Filmarbeit in Frankfurt waren Sie als Schauspieler an mehreren seiner Produktionen beteiligt. Zudem brachten Sie ein Fotobuch zu Fassbinders letztem Film 'Querelle' heraus. Haben Sie etwas von Fassbinders Frankfurt-Dreh mitbekommen, hat Sie sein Film vielleicht sogar beeinflusst? Und hat Fassbinder Ihren Film wiederum gesehen?",
            "Ich habe immer meine eigenen Sachen gemacht und mich trotz meiner Beteiligungen nicht sehr um Fassbinders Arbeit gekümmert. Von seinem Frankfurter Film habe ich gar nichts mitbekommen. Meinen Film wird er auch nicht gesehen haben, da bin ich mir ziemlich sicher. Da blieb ihm gar keine Zeit für. Aber er hat mich sehr verehrt, weil ich Assistent bei Visconti war. 1982 hatte Fassbinder den Falco-Song 'Der Kommissar' kurz nach dessen Erscheinen zu einem Drehbuch ausgearbeitet, das er in den Hauptrollen mit Hanno Pöschl und mir besetzte. Dazu ist es dann durch seinen Tod nicht mehr gekommen. In meinem Frankfurter Film gibt es indirekt über zwei Schauspieler eine Verbindung zu Fassbinder, die beide seinem engeren Kreis angehörten: Isolde Barth, die die Sekretärin meines Ganoven Johnny spielt, und Kurt Raab, der den in eleganten Frauenkleidern steckenden schwulen Onkel der Hauptfigur Susanne spielt. Kurt Raabs Lili Marleen-Szene in meinem Film ist übrigens eine der erstaunlichsten Sachen, die er je gemacht hat, wie ich finde.",
            "Zudem gibt es einen fabelhaften Dialog zwischen dem von Kurt Raab gespielten Onkel Ossi und dessen Lebensgefährten, als dieser ihn fragt: 'Aber glaubst du, dass die Normalen kein Recht auf Liebe haben? Das sind doch auch Menschen, oder?' Eine noch heute eindrucksvolle Wendung.",
            "Wissen Sie, ich denke sehr frei über diese Dinge, ohne große Einschränkungen. Ich habe ja auch mit sehr vielen Leuten, die homosexuell waren, gearbeitet. Neben dem erwähnten Luchino Visconti, dem ich in Rom assistierte, lebte ich ebendort zusammen mit Helmut Berger. Auch habe ich für den Fotografen Herbert List gearbeitet. Ich erinnere mich noch gut daran, wie der Bruder meiner Mutter ihr einen Brief geschrieben hat, in dem stand: Stell Dir mal vor, Dein Junge arbeitet bei einem schwulen italienischen Regisseur!",
            "Der Untertitel Ihres Films lautet: Eine Stadt als Nachtasyl. Wo fanden Sie nachts Asyl in Frankfurt?",
            "Da gab es den Gerhard Schüler, der das 'Plastik' und diese ganzen Kneipen hatte. Er war ein Freund von mir aus Mannheim. In meiner freien Zeit bin ich immer nur in seine Lokale gegangen. Er hat ja auch das 'Dorian Gray' im Frankfurter Flughafen gegründet. 1978 war ich bei dessen Eröffnung. Damals sind wir aus München eigens mit einem Sonderzug angereist, der direkt in den Flughafen einfuhr.",
            "Ihre weibliche Hauptfigur kellnert zeitweise in einem aberwitzigen, damals tatsächlich existierenden Außenlokal namens Bierwiese, einer Art Eckbrachen-Biergarten, wo ein Gast sie mit der zeitgemäßen, man würde heute sagen, Pick-Up-Line konfrontiert: 'Bring mir mal eine Bockwurst, die so knackig ist wie du.' Sie kontert trocken: 'Wir haben nur Frankfurter!' Da ist im Kleinen präsent, was Ihren Film im Ganzen durchzieht: Er schildert das Machtverhältnis zwischen den Geschlechtern, bei dem die scheinbare Souveränität der Männer im Dialog fortwährend subtil gewendet wird. War ihr Film vielleicht zu doppelzüngig, äußerlich zu trivial, um in seiner Qualität als Autorenfilm Würdigung zu finden?",
            "Der Film ist zweifellos ein Autorenfilm. Dass er die diesbezügliche Wahrnehmung nicht erhalten hat, ist meiner Meinung nach schlichtweg der Tatsache geschuldet, dass er als Lisa-Film erschien. Aber mir war das herzlich egal. Es war zu der Zeit, als ich im Grunde in Italien gelebt habe. Letztlich habe ich mich mein ganzes Leben nicht für diese Vereinsmeierei und Einordnungen interessiert. Fragen Sie einmal Roland Klick, den ich für einen der wirklich guten Regisseure halte, der wird Ihnen gleiches sagen. Am Ende ist es das Problem der Leute, die auf solche Einordnungen viel geben und dadurch nicht die hintere Ebene des Films sehen können.",
            "'Frankfurt Kaiserstraße' war Ihr letzter Spielfilm, warum?",
            "Ich habe noch öfter über weitere Spielfilme nachgedacht. Bei mir liegen auch ein paar Drehbücher herum. Eines hatte ich gemeinsam mit Ulf Miehe verfasst. Einmal kam es sogar noch zum Dreh, während dem allerdings relativ schnell die Produktionsfirma pleite ging. Und dann hatte ich auf einmal zwei Lokale in München, die ich eigentlich gar nicht haben wollte."
        ]
    }
];

module.exports = { interviews }





